
    drop table case if exists;

    drop table case_section if exists;

    drop table case_status if exists;

    drop table education_record if exists;

    drop table employment_record if exists;

    create table case (
        id bigint generated by default as identity,
        version bigint not null,
        primary key (id)
    );

    create table case_section (
        id bigint generated by default as identity,
        version bigint not null,
        primary key (id)
    );

    create table case_status (
        id bigint generated by default as identity,
        version bigint not null,
        primary key (id)
    );

    create table education_record (
        id bigint generated by default as identity,
        version bigint not null,
        primary key (id)
    );

    create table employment_record (
        id bigint generated by default as identity,
        version bigint not null,
        primary key (id)
    );
